### ISSUE TITLE
Add Stats 

### ISSUE THREAD

**Issue by nikocrypo** [ShrimpSwap/shrimpswap-frontend#15]
Adding Stats (also overtime, when started etc) to start a TVL contest

![image](https://user-images.githubusercontent.com/36257624/117840064-1ac8fb00-b27c-11eb-9009-93a6884be2b4.png)

**Comment by pedersonshrimp** [comment]
We've added this with https://github.com/ShrimpSwap/shrimpswap-frontend/pull/14
